(define mozc-on-key '("<Meta> "))
(define mozc-on-key? (make-key-predicate '("<Meta> ")))
(define mozc-off-key '("<Meta> "))
(define mozc-off-key? (make-key-predicate '("<Meta> ")))
(define mozc-kana-toggle-key '())
(define mozc-kana-toggle-key? (make-key-predicate '()))
(define mozc-vi-escape-key '("escape" "<Control>["))
(define mozc-vi-escape-key? (make-key-predicate '("escape" "<Control>[")))
